export enum ActionType {
  ADD_ORDER_TO_CART = 'ADD_ORDER_TO_CART',
  INCREASE_ORDER_IN_CART = 'INCREASE_ORDER_IN_CART',
  DECREASE_ORDER_IN_CART = 'DECREASE_ORDER_IN_CART',
  DELETE_ORDER_IN_CART = 'DELETE_ORDER_IN_CART',
}
